import { MetadataRoute } from 'next'

export const dynamic = 'force-static'

export default function sitemap(): MetadataRoute.Sitemap {
    const baseUrl = 'https://hylst.fr/greenit'
    const routes = [
        '',
        '/comprendre',
        '/agir',
        '/outils',
        '/faq',
        '/a-propos',
        '/actualites',
        '/blog',
        '/blog/premier-audit-green-it-pme',
        '/blog/reconditionne-vs-neuf-le-calcul',
        '/blog/comprendre-le-pue-en-5-minutes',
        '/blog/agec-reen-ce-qui-change',
        '/blog/un-an-avec-un-smartphone-reparable',
        '/blog/back-market-portrait-reconditionne',
        '/blog/que-consomme-vraiment-votre-box',
        '/blog/fairphone-portrait-telephone-equitable',
        '/blog/envie-portrait-reemploi-solidaire',
        '/blog/rgesn-ecoconception-10-minutes',
        '/blog/bonus-reparation-mode-emploi',
        '/blog/ia-generative-avis-ademe-2026',
        '/blog/greenwashing-numerique-reperes',
        '/cas-pratiques',
        '/chiffres',
        '/datacenters',
        '/developpement',
        '/fai-box',
        '/fiches-pratiques',
        '/fiches-pratiques/gestes-quotidiens',
        '/fiches-pratiques/achat-responsable',
        '/fiches-pratiques/ecoconception-web',
        '/fiches-pratiques/reparer-prolonger',
        '/fiches-pratiques/green-it-entreprise',
        '/fiches-pratiques/recyclage-mode-emploi',
        '/fiches-pratiques/datacenters-verts',
        '/fiches-pratiques/collectivites-action',
        '/fiches-pratiques/ia-generative',
        '/fiches-pratiques/streaming-video',
        '/fiches-pratiques/teletravail-visio',
        '/fiches-pratiques/emails-cloud',
        '/fiches-pratiques/objets-connectes',
        '/fiches-pratiques/impression-papier',
        '/fiches-pratiques/enfants-ecole',
        '/fiches-pratiques/box-wifi',
        '/guide',
        '/mentions-legales',
        '/modeles',
        '/mythes',
        '/par-ou-commencer',
        '/perspectives',
        '/problematiques',
        '/recyclage',
        '/reglementation',
        '/ressources',
        '/sitemap-page',
        '/modeles/cahier-charges-achat',
        '/modeles/charte-green-it',
        '/modeles/grille-audit',
        '/modeles/guide-sensibilisation',
        '/modeles/plan-action-dsi',
        '/modeles/politique-numerique',
        '/modeles/tableau-bord-impact',
    ]

    return routes.map((route) => ({
        url: `${baseUrl}${route}/`,
        lastModified: '2026-09-16',
        changeFrequency: 'monthly',
        priority: route === '' ? 1 : 0.8,
    }))
}
