// Structure du site en un seul endroit (périmètre minimal, voir ci-dessous).
//
// - SITE_ROUTES : les 61 chemins du sitemap (consommé par app/sitemap.ts).
//   '' = accueil. Ordre conservé tel quel.
// - SEGMENT_LABELS : libellé français de chaque segment d'URL pour le fil
//   d'Ariane (consommé par components/breadcrumb.tsx). Segment inconnu =
//   repli « tirets vers espaces », géré par le composant.
//
// Frontière assumée : la navigation, la recherche et la page « Plan du site »
// gardent leurs propres listes. Leurs libellés sont contextuels et divergent
// volontairement (« Dossiers & veille » en nav, « Dossiers et veille » en
// fil d'Ariane, « Dossiers & veille RSS » en recherche) : les fusionner
// changerait du texte visible. Ne pas « harmoniser » ces libellés au passage.

// --- Sitemap : 61 chemins ('' = accueil) ---
export const SITE_ROUTES: string[] = [
  '',
  '/comprendre',
  '/agir',
  '/outils',
  '/faq',
  '/a-propos',
  '/actualites',
  '/blog',
  '/blog/premier-audit-green-it-pme',
  '/blog/reconditionne-vs-neuf-le-calcul',
  '/blog/comprendre-le-pue-en-5-minutes',
  '/blog/agec-reen-ce-qui-change',
  '/blog/un-an-avec-un-smartphone-reparable',
  '/blog/back-market-portrait-reconditionne',
  '/blog/que-consomme-vraiment-votre-box',
  '/blog/fairphone-portrait-telephone-equitable',
  '/blog/envie-portrait-reemploi-solidaire',
  '/blog/rgesn-ecoconception-10-minutes',
  '/blog/bonus-reparation-mode-emploi',
  '/blog/ia-generative-avis-ademe-2026',
  '/blog/greenwashing-numerique-reperes',
  '/cas-pratiques',
  '/chiffres',
  '/datacenters',
  '/developpement',
  '/fai-box',
  '/fiches-pratiques',
  '/fiches-pratiques/gestes-quotidiens',
  '/fiches-pratiques/achat-responsable',
  '/fiches-pratiques/ecoconception-web',
  '/fiches-pratiques/reparer-prolonger',
  '/fiches-pratiques/green-it-entreprise',
  '/fiches-pratiques/recyclage-mode-emploi',
  '/fiches-pratiques/datacenters-verts',
  '/fiches-pratiques/collectivites-action',
  '/fiches-pratiques/ia-generative',
  '/fiches-pratiques/streaming-video',
  '/fiches-pratiques/teletravail-visio',
  '/fiches-pratiques/emails-cloud',
  '/fiches-pratiques/objets-connectes',
  '/fiches-pratiques/impression-papier',
  '/fiches-pratiques/enfants-ecole',
  '/fiches-pratiques/box-wifi',
  '/guide',
  '/mentions-legales',
  '/modeles',
  '/mythes',
  '/par-ou-commencer',
  '/perspectives',
  '/problematiques',
  '/recyclage',
  '/reglementation',
  '/ressources',
  '/sitemap-page',
  '/modeles/cahier-charges-achat',
  '/modeles/charte-green-it',
  '/modeles/grille-audit',
  '/modeles/guide-sensibilisation',
  '/modeles/plan-action-dsi',
  '/modeles/politique-numerique',
  '/modeles/tableau-bord-impact',
]

// --- Fil d'Ariane : libellé par segment d'URL ---
export const SEGMENT_LABELS: Record<string, string> = {
  "par-ou-commencer": "Par où commencer",
  comprendre: "Comprendre",
  problematiques: "Problématiques",
  mythes: "Mythes vs Réalités",
  reglementation: "Réglementation",
  chiffres: "Chiffres & Données",
  "cas-pratiques": "Cas pratiques",
  agir: "Comment agir",
  datacenters: "Datacenters",
  developpement: "Développement",
  "fai-box": "Choisir son FAI / sa box",
  recyclage: "Recyclage",
  perspectives: "Perspectives",
  outils: "Outils",
  ressources: "Ressources",
  "a-propos": "À propos",
  actualites: "Dossiers et veille",
  blog: "Blog",
  "premier-audit-green-it-pme": "Premier audit Green IT en PME",
  "reconditionne-vs-neuf-le-calcul": "Reconditionné ou neuf",
  "comprendre-le-pue-en-5-minutes": "Comprendre le PUE",
  "agec-reen-ce-qui-change": "AGEC et REEN",
  "un-an-avec-un-smartphone-reparable": "Un an avec un smartphone réparable",
  "back-market-portrait-reconditionne": "Back Market : portrait",
  "que-consomme-vraiment-votre-box": "Que consomme votre box ?",
  "fairphone-portrait-telephone-equitable": "Fairphone : portrait",
  "envie-portrait-reemploi-solidaire": "Envie : portrait",
  "rgesn-ecoconception-10-minutes": "RGESN en 10 minutes",
  "bonus-reparation-mode-emploi": "Bonus réparation",
  "ia-generative-avis-ademe-2026": "IA générative et ADEME",
  faq: "FAQ",
  "fiches-pratiques": "Fiches pratiques",
  "sitemap-page": "Plan du site",
  guide: "Guide",
  "mentions-legales": "Mentions légales",
  offline: "Hors-ligne",
  "gestes-quotidiens": "Gestes quotidiens",
  "achat-responsable": "Achat responsable",
  "ecoconception-web": "Écoconception web",
  "reparer-prolonger": "Réparer et prolonger",
  "green-it-entreprise": "Green IT en entreprise",
  "recyclage-mode-emploi": "Recyclage mode d'emploi",
  "datacenters-verts": "Datacenters et cloud",
  "collectivites-action": "Collectivités",
  "plan-action-dsi": "Plan d'action DSI",
  "politique-numerique": "Politique numérique",
  "grille-audit": "Grille d'audit",
  "cahier-charges-achat": "Cahier des charges",
  "guide-sensibilisation": "Guide de sensibilisation",
  "tableau-bord-impact": "Tableau de bord",
  "charte-green-it": "Charte Green IT",
  modeles: "Modèles téléchargeables",
}
